version: '3.7'

services:
  db:
    image: ${POSTGRES_USER}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}"
    volumes:
    - ./script/init.sql:/docker-entrypoint-initdb.d/init.sql